<script setup lang="ts">
  import { ref, computed, watch, nextTick, onMounted, onUnmounted } from 'vue';
  import type { ComputedRef } from 'vue';

  const props = defineProps<{
    open: boolean;
  }>();

  const emit = defineEmits<{
    select: [emoji: string];
    close: [];
  }>();

  const pickerEl = ref<HTMLElement | null>(null);
  const posX = ref(0);
  const posY = ref(0);

  // ─── Recently-used persistence ────────────────────────────────────────────
  const RECENT_STORAGE_KEY = 'ghostmesh:emoji-recent';
  const RECENT_CAP = 24;

  function loadRecents(): string[] {
    try {
      const raw = localStorage.getItem(RECENT_STORAGE_KEY);
      if (!raw) return [];
      const parsed: unknown = JSON.parse(raw);
      return Array.isArray(parsed)
        ? parsed.filter((s): s is string => typeof s === 'string').slice(0, RECENT_CAP)
        : [];
    } catch {
      return [];
    }
  }

  function saveRecents(list: string[]): void {
    try {
      localStorage.setItem(RECENT_STORAGE_KEY, JSON.stringify(list));
    } catch {
      // localStorage quota or disabled — silent fail
    }
  }

  const recents = ref<string[]>(loadRecents());

  function pushRecent(emoji: string): void {
    const next: string[] = [emoji, ...recents.value.filter((e) => e !== emoji)].slice(
      0,
      RECENT_CAP,
    );
    recents.value = next;
    saveRecents(next);
  }

  function onSelect(emoji: string): void {
    pushRecent(emoji);
    emit('select', emoji);
  }

  /** Position the picker above the trigger button using its DOM rect. */
  function updatePosition() {
    if (!pickerEl.value) return;
    // The Teleport moves us to body, so walk up from the ref's original mount parent
    // Instead, find the trigger button via the wrapper's data attribute
    const trigger = document.querySelector('[data-emoji-trigger]');
    if (!trigger) return;
    const rect = trigger.getBoundingClientRect();
    posX.value = Math.max(8, rect.right - 320);
    posY.value = rect.top - 328;
    if (posY.value < 8) posY.value = 8;
  }

  interface EmojiCategory {
    icon: string;
    label: string;
    emojis: string[];
  }

  const baseCategories: EmojiCategory[] = [
    {
      icon: '😀',
      label: 'Smileys',
      emojis: [
        '😀',
        '😃',
        '😄',
        '😁',
        '😆',
        '😅',
        '🤣',
        '😂',
        '🙂',
        '🙃',
        '😉',
        '😊',
        '😇',
        '🥰',
        '😍',
        '🤩',
        '😘',
        '😗',
        '😚',
        '😙',
        '🥲',
        '😋',
        '😛',
        '😜',
        '🤪',
        '😝',
        '🤑',
        '🤗',
        '🤭',
        '🤫',
        '🤔',
        '🫡',
        '🤐',
        '🤨',
        '😐',
        '😑',
        '😶',
        '🫥',
        '😏',
        '😒',
        '🙄',
        '😬',
        '🤥',
        '😌',
        '😔',
        '😪',
        '🤤',
        '😴',
        '😷',
        '🤒',
        '🤕',
        '🤢',
        '🤮',
        '🥴',
        '😵',
        '🤯',
        '🥳',
        '🥸',
        '😎',
        '🤓',
        '🧐',
        '😕',
        '🫤',
        '😟',
        '🙁',
        '😮',
        '😯',
        '😲',
        '😳',
        '🥺',
        '🥹',
        '😦',
        '😧',
        '😨',
        '😰',
        '😥',
        '😢',
        '😭',
        '😱',
        '😖',
        '😣',
        '😞',
        '😓',
        '😩',
        '😫',
        '🥱',
        '😤',
        '😡',
        '😠',
        '🤬',
        '😈',
        '👿',
        '💀',
        '☠️',
        '💩',
        '🤡',
        '👹',
        '👺',
        '👻',
        '👽',
        '👾',
        '🤖',
        '😺',
        '😸',
        '😹',
        '😻',
        '😼',
        '😽',
        '🙀',
        '😿',
        '😾',
      ],
    },
    {
      icon: '👋',
      label: 'People',
      emojis: [
        '👋',
        '🤚',
        '🖐️',
        '✋',
        '🖖',
        '🫱',
        '🫲',
        '🫳',
        '🫴',
        '🫷',
        '🫸',
        '👌',
        '🤌',
        '🤏',
        '✌️',
        '🤞',
        '🫰',
        '🤟',
        '🤘',
        '🤙',
        '👈',
        '👉',
        '👆',
        '🖕',
        '👇',
        '☝️',
        '🫵',
        '👍',
        '👎',
        '✊',
        '👊',
        '🤛',
        '🤜',
        '👏',
        '🙌',
        '🫶',
        '👐',
        '🤲',
        '🤝',
        '🙏',
        '✍️',
        '💅',
        '🤳',
        '💪',
        '🦾',
        '🦿',
        '🦵',
        '🦶',
        '👂',
        '🦻',
        '👃',
        '🧠',
        '🫀',
        '🫁',
        '🦷',
        '🦴',
        '👀',
        '👁️',
        '👅',
        '👄',
        '🫦',
        '👶',
        '🧒',
        '👦',
        '👧',
        '🧑',
        '👱',
        '👨',
        '🧔',
        '👩',
        '🧓',
        '👴',
        '👵',
        '🙍',
        '🙎',
        '🙅',
        '🙆',
        '💁',
        '🙋',
        '🧏',
        '🙇',
        '🤦',
        '🤷',
        '👮',
        '🕵️',
        '💂',
        '🥷',
        '👷',
        '🫅',
        '🤴',
        '👸',
        '👳',
        '👲',
        '🧕',
        '🤵',
        '👰',
        '🤰',
        '🫃',
        '🫄',
        '🤱',
      ],
    },
    {
      icon: '🐶',
      label: 'Animals',
      emojis: [
        '🐶',
        '🐱',
        '🐭',
        '🐹',
        '🐰',
        '🦊',
        '🐻',
        '🐼',
        '🐻‍❄️',
        '🐨',
        '🐯',
        '🦁',
        '🐮',
        '🐷',
        '🐸',
        '🐵',
        '🙈',
        '🙉',
        '🙊',
        '🐒',
        '🐔',
        '🐧',
        '🐦',
        '🐤',
        '🐣',
        '🐥',
        '🦆',
        '🦅',
        '🦉',
        '🦇',
        '🐺',
        '🐗',
        '🐴',
        '🦄',
        '🐝',
        '🪱',
        '🐛',
        '🦋',
        '🐌',
        '🐞',
        '🐜',
        '🪰',
        '🪲',
        '🪳',
        '🦟',
        '🦗',
        '🕷️',
        '🦂',
        '🐢',
        '🐍',
        '🦎',
        '🦖',
        '🦕',
        '🐙',
        '🦑',
        '🦐',
        '🦞',
        '🦀',
        '🐡',
        '🐠',
        '🐟',
        '🐬',
        '🐳',
        '🐋',
        '🦈',
        '🦭',
        '🐊',
        '🐅',
        '🐆',
        '🪼',
        '🦓',
        '🫏',
        '🦍',
        '🦧',
        '🦣',
        '🐘',
        '🦛',
        '🦏',
        '🐪',
        '🐫',
        '🦒',
        '🦘',
        '🦬',
        '🐃',
        '🐂',
        '🐄',
        '🐎',
        '🐖',
        '🐏',
        '🐑',
        '🦙',
        '🐐',
        '🦌',
        '🫎',
        '🐕',
        '🐩',
        '🦮',
        '🐈',
        '🐓',
        '🦃',
      ],
    },
    {
      icon: '🌿',
      label: 'Nature',
      emojis: [
        '☀️',
        '🌤️',
        '⛅',
        '🌥️',
        '☁️',
        '🌦️',
        '🌧️',
        '⛈️',
        '🌩️',
        '🌨️',
        '❄️',
        '☃️',
        '⛄',
        '☔',
        '☂️',
        '💧',
        '💦',
        '🌊',
        '🌫️',
        '🌪️',
        '🌬️',
        '💨',
        '🌈',
        '⚡',
        '🔥',
        '💥',
        '🌑',
        '🌒',
        '🌓',
        '🌔',
        '🌕',
        '🌖',
        '🌗',
        '🌘',
        '🌙',
        '🌚',
        '🌛',
        '🌜',
        '🌝',
        '🌞',
        '⭐',
        '🌟',
        '✨',
        '☄️',
        '🪐',
        '🌍',
        '🌎',
        '🌏',
        '🌱',
        '🌿',
        '☘️',
        '🍀',
        '🎋',
        '🪴',
        '🌵',
        '🌴',
        '🌳',
        '🌲',
        '🍃',
        '🍂',
        '🍁',
        '🌾',
        '💐',
        '🌷',
        '🌹',
        '🥀',
        '🪷',
        '🌺',
        '🌸',
        '🌼',
        '🌻',
      ],
    },
    {
      icon: '🍔',
      label: 'Food',
      emojis: [
        '🍇',
        '🍈',
        '🍉',
        '🍊',
        '🍋',
        '🍌',
        '🍍',
        '🥭',
        '🍎',
        '🍏',
        '🍐',
        '🍑',
        '🍒',
        '🍓',
        '🫐',
        '🥝',
        '🍅',
        '🫒',
        '🥥',
        '🥑',
        '🍆',
        '🥔',
        '🥕',
        '🌽',
        '🌶️',
        '🫑',
        '🥒',
        '🥬',
        '🥦',
        '🧄',
        '🧅',
        '🥜',
        '🫘',
        '🌰',
        '🫚',
        '🫛',
        '🍞',
        '🥐',
        '🥖',
        '🫓',
        '🥨',
        '🥯',
        '🥞',
        '🧇',
        '🧀',
        '🍖',
        '🍗',
        '🥩',
        '🥓',
        '🍔',
        '🍟',
        '🍕',
        '🌭',
        '🥪',
        '🌮',
        '🌯',
        '🫔',
        '🥙',
        '🧆',
        '🥚',
        '🍳',
        '🥘',
        '🍲',
        '🫕',
        '🥣',
        '🥗',
        '🍿',
        '🧈',
        '🧂',
        '🥫',
        '🍱',
        '🍘',
        '🍙',
        '🍚',
        '🍛',
        '🍜',
        '🍝',
        '🍠',
        '🍢',
        '🍣',
        '🍤',
        '🍥',
        '🥮',
        '🍡',
        '🥟',
        '🥠',
        '🥡',
        '🦀',
        '🦞',
        '🦐',
        '🍦',
        '🍧',
        '🍨',
        '🍩',
        '🍪',
        '🎂',
        '🍰',
        '🧁',
        '🥧',
        '🍫',
        '🍬',
        '🍭',
        '🍮',
        '🍯',
        '☕',
        '🫖',
        '🍵',
        '🍶',
        '🍾',
        '🍷',
        '🍸',
        '🍹',
        '🍺',
        '🍻',
        '🥂',
        '🥃',
        '🫗',
        '🥤',
        '🧋',
        '🧃',
      ],
    },
    {
      icon: '⚽',
      label: 'Activities',
      emojis: [
        '⚽',
        '🏀',
        '🏈',
        '⚾',
        '🥎',
        '🎾',
        '🏐',
        '🏉',
        '🥏',
        '🎱',
        '🪀',
        '🏓',
        '🏸',
        '🏒',
        '🏑',
        '🥍',
        '🏏',
        '🪃',
        '🥅',
        '⛳',
        '🪁',
        '🏹',
        '🎣',
        '🤿',
        '🥊',
        '🥋',
        '🎽',
        '🛹',
        '🛼',
        '🛷',
        '⛸️',
        '🥌',
        '🎿',
        '⛷️',
        '🏂',
        '🪂',
        '🏋️',
        '🤼',
        '🤸',
        '🤺',
        '⛹️',
        '🤾',
        '🏌️',
        '🏇',
        '🧘',
        '🏄',
        '🏊',
        '🤽',
        '🚣',
        '🧗',
        '🚴',
        '🚵',
        '🎪',
        '🎗️',
        '🎟️',
        '🎫',
        '🎖️',
        '🏆',
        '🏅',
        '🥇',
        '🥈',
        '🥉',
        '🎮',
        '🕹️',
        '🎲',
        '🧩',
        '♟️',
        '🎯',
        '🎳',
        '🎭',
        '🎨',
        '🎬',
        '🎤',
        '🎧',
        '🎼',
        '🎹',
        '🥁',
        '🪘',
        '🎷',
        '🎺',
        '🪗',
        '🎸',
        '🎻',
        '🪕',
        '🎶',
        '🎵',
      ],
    },
    {
      icon: '🚗',
      label: 'Travel',
      emojis: [
        '🚗',
        '🚕',
        '🚙',
        '🚌',
        '🚎',
        '🏎️',
        '🚓',
        '🚑',
        '🚒',
        '🚐',
        '🛻',
        '🚚',
        '🚛',
        '🚜',
        '🛵',
        '🏍️',
        '🛺',
        '🚲',
        '🛴',
        '🚏',
        '🛣️',
        '🛤️',
        '🚡',
        '🚠',
        '🚟',
        '🚃',
        '🚋',
        '🚝',
        '🚄',
        '🚅',
        '🚆',
        '🚇',
        '🚈',
        '🚉',
        '✈️',
        '🛫',
        '🛬',
        '💺',
        '🚀',
        '🛸',
        '🚁',
        '🛶',
        '⛵',
        '🚤',
        '🛥️',
        '🛳️',
        '⛴️',
        '🚢',
        '⚓',
        '🪝',
        '⛽',
        '🚧',
        '🚦',
        '🚥',
        '🗺️',
        '🗿',
        '🗽',
        '🗼',
        '🏰',
        '🏯',
        '🏟️',
        '🎡',
        '🎢',
        '🎠',
        '⛲',
        '⛱️',
        '🏖️',
        '🏝️',
        '🏜️',
        '🌋',
        '⛰️',
        '🏔️',
        '🗻',
        '🏕️',
        '🛖',
        '🏠',
        '🏡',
        '🏢',
        '🏣',
        '🏤',
        '🏥',
        '🏦',
        '🏨',
        '🏩',
        '🏪',
        '🏫',
        '🏬',
        '🌁',
        '🌃',
        '🌆',
        '🌇',
        '🌉',
        '🌌',
        '🌠',
        '🎆',
        '🎇',
        '🧨',
        '🎑',
        '🏮',
      ],
    },
    {
      icon: '💡',
      label: 'Objects',
      emojis: [
        '⌚',
        '📱',
        '💻',
        '⌨️',
        '🖥️',
        '🖨️',
        '🖱️',
        '🖲️',
        '🕹️',
        '🗜️',
        '💾',
        '💿',
        '📀',
        '📼',
        '📷',
        '📸',
        '📹',
        '🎥',
        '📽️',
        '🎞️',
        '📞',
        '☎️',
        '📟',
        '📠',
        '📺',
        '📻',
        '🎙️',
        '🎚️',
        '🎛️',
        '🧭',
        '⏱️',
        '⏲️',
        '⏰',
        '🕰️',
        '⌛',
        '⏳',
        '📡',
        '🔋',
        '🪫',
        '🔌',
        '💡',
        '🔦',
        '🕯️',
        '🪔',
        '🧯',
        '🗑️',
        '🛢️',
        '💰',
        '💴',
        '💵',
        '💶',
        '💷',
        '🪙',
        '💳',
        '💎',
        '⚖️',
        '🪜',
        '🧰',
        '🪛',
        '🔧',
        '🔨',
        '⚒️',
        '🛠️',
        '⛏️',
        '🪚',
        '🔩',
        '⚙️',
        '🪤',
        '🧲',
        '🔫',
        '💣',
        '🪓',
        '🔪',
        '🗡️',
        '⚔️',
        '🛡️',
        '🚬',
        '⚰️',
        '🪦',
        '⚱️',
        '🏺',
        '🔮',
        '📿',
        '🧿',
        '🪬',
        '💈',
        '⚗️',
        '🔭',
        '🔬',
        '🕳️',
        '🩹',
        '🩺',
        '🩻',
        '🩼',
        '💊',
        '💉',
        '🩸',
        '🧬',
        '🦠',
        '🧫',
      ],
    },
    {
      icon: '❤️',
      label: 'Symbols',
      emojis: [
        '❤️',
        '🧡',
        '💛',
        '💚',
        '💙',
        '💜',
        '🖤',
        '🤍',
        '🤎',
        '💔',
        '❤️‍🔥',
        '❤️‍🩹',
        '❣️',
        '💕',
        '💞',
        '💓',
        '💗',
        '💖',
        '💘',
        '💝',
        '💟',
        '☮️',
        '✝️',
        '☪️',
        '🕉️',
        '☸️',
        '✡️',
        '🔯',
        '🕎',
        '☯️',
        '☦️',
        '🛐',
        '⛎',
        '♈',
        '♉',
        '♊',
        '♋',
        '♌',
        '♍',
        '♎',
        '♏',
        '♐',
        '♑',
        '♒',
        '♓',
        '🆔',
        '⚛️',
        '🉑',
        '☢️',
        '☣️',
        '📴',
        '📳',
        '🈶',
        '🈚',
        '🈸',
        '🈺',
        '🈷️',
        '✴️',
        '🆚',
        '💮',
        '🉐',
        '㊙️',
        '㊗️',
        '🈴',
        '🈵',
        '🈹',
        '🈲',
        '🅰️',
        '🅱️',
        '🆎',
        '🆑',
        '🅾️',
        '🆘',
        '❌',
        '⭕',
        '🛑',
        '⛔',
        '📛',
        '🚫',
        '💯',
        '💢',
        '♨️',
        '🚷',
        '🚯',
        '🚳',
        '🚱',
        '🔞',
        '📵',
        '🚭',
        '❗',
        '❕',
        '❓',
        '❔',
        '‼️',
        '⁉️',
        '🔅',
        '🔆',
        '〽️',
        '⚠️',
        '🚸',
        '🔱',
        '⚜️',
        '🔰',
        '♻️',
        '✅',
        '🈯',
        '💹',
        '❇️',
        '✳️',
        '❎',
        '🌐',
        '💠',
        'Ⓜ️',
        '🌀',
        '💤',
        '🏧',
        '🚾',
        '♿',
        '🅿️',
        '🛗',
        '🈳',
        '🈂️',
        '🛂',
        '🛃',
        '🛄',
        '🛅',
        '🚹',
        '🚺',
        '🚻',
        '🚼',
        '🚮',
        '🎦',
        '📶',
        '🈁',
        '🔣',
        'ℹ️',
        '🔤',
        '🔡',
        '🔠',
        '🆖',
        '🆗',
        '🆙',
        '🆒',
        '🆕',
        '🆓',
        '0️⃣',
        '1️⃣',
        '2️⃣',
        '3️⃣',
        '4️⃣',
        '5️⃣',
        '6️⃣',
        '7️⃣',
        '8️⃣',
        '9️⃣',
        '🔟',
        '🔢',
        '#️⃣',
        '*️⃣',
        '⏏️',
        '▶️',
        '⏸️',
        '⏯️',
        '⏹️',
        '⏺️',
        '⏭️',
        '⏮️',
        '⏩',
        '⏪',
        '⏫',
        '⏬',
        '◀️',
        '🔼',
        '🔽',
        '➡️',
        '⬅️',
        '⬆️',
        '⬇️',
        '↗️',
        '↘️',
        '↙️',
        '↖️',
        '↕️',
        '↔️',
        '↩️',
        '↪️',
        '⤴️',
        '⤵️',
        '🔀',
        '🔁',
        '🔂',
        '🔄',
        '🔃',
      ],
    },
    {
      icon: '🏁',
      label: 'Flags',
      emojis: [
        '🏳️',
        '🏴',
        '🏁',
        '🚩',
        '🏳️‍🌈',
        '🏳️‍⚧️',
        '🏴‍☠️',
        '🇦🇷',
        '🇦🇺',
        '🇦🇹',
        '🇧🇪',
        '🇧🇷',
        '🇨🇦',
        '🇨🇱',
        '🇨🇳',
        '🇨🇴',
        '🇨🇷',
        '🇨🇺',
        '🇨🇿',
        '🇩🇰',
        '🇪🇨',
        '🇪🇬',
        '🇫🇮',
        '🇫🇷',
        '🇩🇪',
        '🇬🇷',
        '🇭🇰',
        '🇭🇺',
        '🇮🇸',
        '🇮🇳',
        '🇮🇩',
        '🇮🇪',
        '🇮🇱',
        '🇮🇹',
        '🇯🇵',
        '🇰🇷',
        '🇲🇽',
        '🇳🇱',
        '🇳🇿',
        '🇳🇴',
        '🇵🇪',
        '🇵🇭',
        '🇵🇱',
        '🇵🇹',
        '🇷🇴',
        '🇷🇺',
        '🇸🇦',
        '🇸🇬',
        '🇿🇦',
        '🇪🇸',
        '🇸🇪',
        '🇨🇭',
        '🇹🇼',
        '🇹🇭',
        '🇹🇷',
        '🇺🇦',
        '🇬🇧',
        '🇺🇸',
        '🇺🇾',
        '🇻🇪',
        '🇻🇳',
      ],
    },
  ];

  /** Categories with an optional "Recent" tab prepended when recents is non-empty. */
  const categories: ComputedRef<EmojiCategory[]> = computed(() =>
    recents.value.length === 0
      ? baseCategories
      : [{ icon: '🕒', label: 'Recent', emojis: recents.value }, ...baseCategories],
  );

  /** Active category by label (stable across recents tab appearing/disappearing). */
  const activeCategory = ref<string>(recents.value.length > 0 ? 'Recent' : 'Smileys');

  const activeEmojis: ComputedRef<string[]> = computed(
    () => categories.value.find((c) => c.label === activeCategory.value)?.emojis || [],
  );

  watch(
    () => props.open,
    (val) => {
      if (!val) return;
      // Default to Recent when available; otherwise fall back to the first visible tab.
      if (recents.value.length > 0) activeCategory.value = 'Recent';
      else if (!categories.value.some((c) => c.label === activeCategory.value)) {
        activeCategory.value = categories.value[0]?.label || 'Smileys';
      }
      nextTick(updatePosition);
    },
  );

  /** Close picker on outside click. */
  function onClickOutside(e: MouseEvent) {
    if (pickerEl.value && !pickerEl.value.contains(e.target as Node)) {
      emit('close');
    }
  }

  onMounted(() => document.addEventListener('mousedown', onClickOutside));
  onUnmounted(() => document.removeEventListener('mousedown', onClickOutside));
</script>

<template>
  <Teleport to="body">
    <div
      v-if="open"
      ref="pickerEl"
      class="fixed z-[100] flex h-80 w-80 flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl"
      :style="{ left: posX + 'px', top: posY + 'px' }"
    >
      <!-- Category tabs -->
      <div class="flex shrink-0 border-b border-slate-100">
        <button
          v-for="cat in categories"
          :key="cat.label"
          class="flex-1 py-2 text-center text-base transition-colors"
          :class="activeCategory === cat.label ? 'bg-slate-50 shadow-inner' : 'hover:bg-slate-50'"
          :data-tooltip="cat.label"
          @click="activeCategory = cat.label"
        >
          {{ cat.icon }}
        </button>
      </div>
      <!-- Emoji grid -->
      <div class="flex-1 overflow-y-auto p-2">
        <div class="grid grid-cols-8 gap-0.5">
          <button
            v-for="emoji in activeEmojis"
            :key="emoji"
            class="flex h-8 w-8 items-center justify-center rounded text-lg transition-colors hover:bg-slate-100"
            @click="onSelect(emoji)"
          >
            {{ emoji }}
          </button>
        </div>
      </div>
    </div>
  </Teleport>
</template>
